export const homeObjOne = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "about us",
  headline: "Edgar Rincón Morán",
  description: "Web Developer & CEO Standards Apps",
  buttonLabel: "Meet Edgar",
  imgStart: "start",
  img: "https://github.com/edgarrincon/StandardApp/blob/main/src/img/EdgarCapitolio.jpg?raw=true",
  alt: "Edgar Rincon",
  linkTo: "./edgar",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};

export const homeObjTwo = {
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "about us",
  headline: "Victor Quintero",
  description: "Web Developer & Cofunder Standards Apps",
  buttonLabel: "Meet Victor",
  imgStart: "",
  img: "https://github.com/edgarrincon/StandardApp/blob/main/src/img/victorLasVegas.jpg?raw=true",
  alt: "Victor Quintero",
  linkTo: "./victor",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};
export const homeObjTheree = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "about us",
  headline: "Standards Apps",
  description:
    "The pyramids were the first Standard buildings, they are simple, efficient, and still there ; )",
  buttonLabel: "Take a look",
  imgStart: "start",
  img: "https://raw.githubusercontent.com/edgarrincon/StandardApp/main/src/img/logo.png",
  alt: "Edgar Rincon",
  linkTo: "./",
  buttonSize: "btn--wide",
  buttonColor: "yellow",
};
